### ISSUE TITLE
JsonParser is missing

### ISSUE THREAD

**Issue by amaumont** [jgrapht/jgrapht#986]
```
 * JGraphT version: not relevant
 * Java version (java -version)/platform:  not relevant
```

**Issue**

`org.jgrapht.nio.json.JsonParser` is missing in `org.jgrapht.nio.json.JSONEventDrivenImporter`, I cannot find in at `/jgrapht/jgrapht-io/src/main/java/org/jgrapht/nio/json`, is it located elsewhere?

Do I miss something?

Thank you.

**Steps to reproduce (small coding example)**

Trying to compile in intelliJ 2019.1.3.

**Expected behaviour**

No compilation error.

**Other information**

**Comment by d-michail** [comment]
Please do not open issues for such questions. Best to use the jgrapht-users mailing list. 

To answer your question, this source file is auto-generated during compilation. See [here](https://github.com/jgrapht/jgrapht/wiki/Dev-guide%3A-How-to-setup-your-development-environment-for-JGraphT) for more details on how to import a maven project from IntelliJ. The important step is the `Maven->Generate Sources and Update Folders` on the jgrapht-io project.

**Comment by amaumont** [comment]
> Please do not open issues for such questions. Best to use the jgrapht-users mailing list.

Thank you for information, yes I will ask in mailing list sorry for that.
